gupnp-linux-context-manager.c: fix {linux,net}/if.h redefinition
Do not include net/if.h if linux/wireless.h is available otherwise build
will fail due to redefinitions like struct ifmap:

In file included from /home/fabrice/buildroot/output/host/mips64el-buildroot-linux-gnu/sysroot/usr/include/linux/wireless.h:74:0,
                 from ../libgupnp/gupnp-linux-context-manager.c:52:
/home/fabrice/buildroot/output/host/mips64el-buildroot-linux-gnu/sysroot/usr/include/linux/if.h:169:8: error: redefinition of 'struct ifmap'
 struct ifmap {
        ^
In file included from ../libgupnp/gupnp-linux-context-manager.c:50:0:
/home/fabrice/buildroot/output/host/mips64el-buildroot-linux-gnu/sysroot/usr/include/net/if.h:111:8: note: originally defined here
 struct ifmap

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>