Test suite needs libxml2
Without that build test suite binaties fails

```console
+ /usr/bin/meson compile -C x86_64-redhat-linux-gnu -j 48 --verbose
ninja: Entering directory `/home/tkloczko/rpmbuild/BUILD/gupnp-1.5.3/x86_64-redhat-linux-gnu'
[1/66] /usr/bin/gcc -Itests/test-service.p -Itests -I../tests -Iinternal -I../internal -I. -I.. -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gssdp-1.6 -I/usr/include/libsoup-3.0 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -Werror=deprecated-declarations -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -pthread '-DDATA_PATH="/home/tkloczko/rpmbuild/BUILD/gupnp-1.5.3/tests/data"' -MD -MQ tests/test-service.p/test-service.c.o -MF tests/test-service.p/test-service.c.o.d -o tests/test-service.p/test-service.c.o -c ../tests/test-service.c
FAILED: tests/test-service.p/test-service.c.o
/usr/bin/gcc -Itests/test-service.p -Itests -I../tests -Iinternal -I../internal -I. -I.. -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gssdp-1.6 -I/usr/include/libsoup-3.0 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -Werror=deprecated-declarations -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -pthread '-DDATA_PATH="/home/tkloczko/rpmbuild/BUILD/gupnp-1.5.3/tests/data"' -MD -MQ tests/test-service.p/test-service.c.o -MF tests/test-service.p/test-service.c.o.d -o tests/test-service.p/test-service.c.o -c ../tests/test-service.c
In file included from ../tests/test-service.c:5:
../libgupnp/gupnp-xml-doc.h:15:10: fatal error: libxml/tree.h: No such file or directory
   15 | #include <libxml/tree.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
```

Signed-off-by: Tomasz Kłoczko <kloczek@github.com>